# Generated by Django 4.2.7 on 2025-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_hub', '0003_question_answer_questionvote_answervote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='downvote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
