# Generated by Django 5.0.1 on 2025-01-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donationcampaign_donation_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
