# Generated by Django 4.2.7 on 2025-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='expertise',
            field=models.TextField(blank=True, help_text='Detailed expertise description', null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='motivation',
            field=models.TextField(blank=True, help_text='Motivation for joining the project', null=True),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='skills',
            field=models.JSONField(default=list, help_text='Skills relevant to this project'),
        ),
    ]
