# Generated by Django 4.2.7 on 2025-05-03 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_board_column_task_taskcomment_taskassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveIntegerField(help_text='Week number for this progress log')),
                ('week_start_date', models.DateField(help_text='Start date for the week')),
                ('summary', models.TextField(help_text='Summary of work done this week')),
                ('blockers', models.TextField(blank=True, help_text='Any blockers or challenges faced', null=True)),
                ('goals_next_week', models.TextField(blank=True, help_text='Goals for next week', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='projects.workspace')),
            ],
            options={
                'ordering': ['-week_start_date', '-created_at'],
                'unique_together': {('workspace', 'user', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgressLogTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('not_started', 'Not Started')], max_length=20)),
                ('contribution', models.TextField(help_text='Work done on this specific task')),
                ('hours_spent', models.PositiveIntegerField(default=0, help_text='Hours spent on this task')),
                ('progress_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.progresslog')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.task')),
            ],
            options={
                'unique_together': {('progress_log', 'task')},
            },
        ),
    ]
