# Generated by Django 4.2.7 on 2025-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvitation',
            name='message',
            field=models.TextField(blank=True, help_text='Invitation message', null=True),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
