# Generated by Django 4.2.7 on 2025-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_funding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={},
        ),
        migrations.AddField(
            model_name='funding',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='funding',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
