# Generated by Django 4.2.7 on 2025-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_funding_options_funding_collected_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='funding_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
