# Generated by Django 4.2.7 on 2025-05-06 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)])),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WordleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('daily_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.dailyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-daily_word__date', 'end_time'],
                'unique_together': {('user', 'daily_word')},
            },
        ),
        migrations.CreateModel(
            name='WordleGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='games.wordlegame')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
