# Generated by Django 4.2.7 on 2025-05-06 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionsSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionsWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='games.connectionsgroup')),
            ],
        ),
        migrations.AddField(
            model_name='connectionsgroup',
            name='connections_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='games.connectionsset'),
        ),
        migrations.CreateModel(
            name='ConnectionsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('mistakes', models.PositiveSmallIntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('groups_found', models.JSONField(default=list)),
                ('connections_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.connectionsset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-connections_set__date', 'end_time'],
                'unique_together': {('user', 'connections_set')},
            },
        ),
    ]
