# Generated by Django 4.2.7 on 2025-05-06 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_connectionsgroup_connectionsset_connectionsword_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectionsgame',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='connectionsgame',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectionsgroup',
            name='domain',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('electrical_electronics', 'Electrical & Electronics'), ('mechanical', 'Mechanical'), ('aeronautical', 'Aeronautical')], default='computer_science', max_length=50),
        ),
        migrations.AddField(
            model_name='connectionsgroup',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='connectionsgame',
            unique_together={('user', 'connections_set', 'domain')},
        ),
    ]
