# Generated by Django 5.0.1 on 2025-01-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='application_url',
            field=models.URLField(help_text="URL to the company's job application portal"),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
