# Generated by Django 5.1.4 on 2025-01-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ALUMNI', 'Alumni'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], default='ALUMNI', max_length=10),
        ),
    ]
