# Generated by Django 4.2.7 on 2025-04-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_alter_followrequest_options_and_more'),
    ]

    operations = [
    ]
