# Generated by Django 4.2.7 on 2025-05-05 13:02

from django.db import migrations, models

def set_media_types(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    # Set media_type to 'image' for existing posts with media
    posts_with_media = Post.objects.exclude(media='').exclude(media__isnull=True)
    for post in posts_with_media:
        post.media_type = 'image'
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_poll_post_is_poll_polloption_poll_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.RunPython(set_media_types, migrations.RunPython.noop),
    ]
